### ISSUE TITLE
MOSFIRE 2018 release

### ISSUE THREAD

**Issue by lyanatcit** [Keck-DataReductionPipelines/MosfireDRP#130]
Hi, I just downloaded the 2018 release, and tried on the example data. I got the following error while running "Wavelength.fit_lambda".   

mospy Driver.py
2018-12-05 10:23:10,279 - MosfireDrpLog.            <module> - INFO: 3.6.3 |Anaconda, Inc.| (default, Dec  5 2017, 17:30:25) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
2018-12-05 10:23:10,279 - MosfireDrpLog.            <module> - INFO: python version = 3.6.3
2018-12-05 10:23:10,279 - MosfireDrpLog.            <module> - INFO: numpy version = 1.13.3
2018-12-05 10:23:10,279 - MosfireDrpLog.            <module> - INFO: matplotlib version = 2.1.1
2018-12-05 10:23:10,279 - MosfireDrpLog.            <module> - INFO: astropy version = 2.0.3
2018-12-05 10:23:10,279 - MosfireDrpLog.            <module> - INFO: ccdproc version = 1.3.0
2018-12-05 10:23:10,377 -   Wavelength.          fit_lambda - INFO: MOSFIRE_DRP_MASK] Writing to: lambda_coeffs_wave_stack_H_m120910_0163-0176.npy
2018-12-05 10:23:10,529 -   Wavelength.   fit_lambda_helper - INFO: * Fitting Slit TARG7 from 1952 to 2032
2018-12-05 10:23:10,531 -   Wavelength.  fit_outwards_refit - INFO: Computing 0 spectrum at 1990
2018-12-05 10:24:25,233 -   Wavelength.   fit_lambda_helper - INFO: S01] TOOK: 74 s
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/lyan/anaconda3/envs/mospy_2018_macos/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/lyan/anaconda3/envs/mospy_2018_macos/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/lyan/anaconda3/envs/mospy_2018_macos/lib/python3.6/site-packages/MOSFIRE-1.0.dev3-py3.6.egg/MOSFIRE/Wavelength.py", line 392, in fit_lambda_helper
    sol_1d = center_solutions[slitidx]["sol_1d"]
TypeError: 'int' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Driver.py", line 36, in <module>
    Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles,waveops)
  File "/Users/lyan/anaconda3/envs/mospy_2018_macos/lib/python3.6/site-packages/MOSFIRE-1.0.dev3-py3.6.egg/MOSFIRE/Wavelength.py", line 365, in fit_lambda
    solutions = p.map(fit_lambda_helper, list(range(len(bs.ssl))))
  File "/Users/lyan/anaconda3/envs/mospy_2018_macos/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/lyan/anaconda3/envs/mospy_2018_macos/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: 'int' object is not subscriptable

**Comment by joshwalawender** [comment]
@lyanatcit Usually this is caused by an incomplete wavelength fit.  The next version of the DRP will have better messaging to use the user about this, but just re-run the DRP and make sure you do the interactive fit for all slits until the graphics window says "DONE!" in red letters over the plot.
