### ISSUE TITLE
Issue when creating the conda environnement

### ISSUE THREAD

**Issue by NicolasLaporte** [Keck-DataReductionPipelines/MosfireDRP#145]
Hi, 

I got the following issue when creating my conda environnement, I am wondering if this is just not a repository issue : 

`(base) nlaporte@nicolass-macbook-pro-2 J % conda env create KeckObservatory/mospy_2018_macos     
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - zope==1.0=py36_0
`

Any idea how I can solve this ? 
Many thanks in advance

**Comment by joshwalawender** [comment]
Hi @NicolasLaporte , I will try to work up a new environment file and get that out later today.

-Josh

**Comment by joshwalawender** [comment]
@NicolasLaporte Try using [this environment file](https://www.dropbox.com/s/3eqkbtlqo0c7vw0/mospy.yaml?dl=0) (note this is a temporary link).

Install the environment using:
```
conda env create -f mospy.yaml
```

If it works for you, I'll put it in the repo for others to use.

-Josh

**Comment by NicolasLaporte** [comment]
Dear Josh,

Thanks for your quick answer.
I can now create the mospy environment but when typing “mospy AutoDriver” I get the error “mospy: command not found”.
I think there is just a link missing in the .yaml file to install the pipeline, no ?

Thanks.
Nicolas

**Comment by NicolasLaporte** [comment]
Please forget my last message…

I downloaded the MOSFIRE zip package, and I get the following issue when running “python setup.py install”

(mospy) nicolass-macbook-pro-2:MosfireDRP-master nlaporte$ python3.6 setup.py install

The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.  Attempting download instead.

Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.

Traceback (most recent call last):

  File "setup.py", line 18, in <module>

    from astropy_helpers.setup_helpers import (

ModuleNotFoundError: No module named 'astropy_helpers.setup_helpers'

Best regards
Nicolas

**Comment by NicolasLaporte** [comment]
Dear Josh,

I solved the problem by doing a simple “pip install astropy-helpers==3.1“

Now it works perfectly,

Many thanks for your help,

Nicolas


From: "Laporte, Nicolas" <n.laporte@ucl.ac.uk>
Date: Monday, 7 September 2020 at 08:02
To: Keck-DataReductionPipelines/MosfireDRP <reply@reply.github.com>, Keck-DataReductionPipelines/MosfireDRP <MosfireDRP@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [Keck-DataReductionPipelines/MosfireDRP] Issue when creating the conda environnement (#145)

Please forget my last message…

I downloaded the MOSFIRE zip package, and I get the following issue when running “python setup.py install”

(mospy) nicolass-macbook-pro-2:MosfireDRP-master nlaporte$ python3.6 setup.py install

The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.  Attempting download instead.

Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.

Traceback (most recent call last):

  File "setup.py", line 18, in <module>

    from astropy_helpers.setup_helpers import (

ModuleNotFoundError: No module named 'astropy_helpers.setup_helpers'

Best regards
Nicolas

**Comment by monodera** [comment]
I have the same issue on macOS 10.15.7 and conda 4.9.2.  When I tried the updated mospy.yaml file above with `conda env create -f mospy.yaml`, I got the following error and the environment was not created. 

```
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                     /
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                     |

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package numpy conflicts for:
ccdproc=1.3.0 -> astropy[version='>=1.0'] -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.10|>=1.11|>=1.13|>=1.14|>=1.16.5,<2.0a0|>=1.16|>=1.19.4,<2.0a0|>=1.19|>=1.17|>=1.9|>=1.19.2,<2.0a0|>=1.16.6,<2.0a0|>=1.17.4,<2.0a0|>=1.14.6,<2.0a0|>=1.13.3,<2.0a0|>=1.11.3,<2.0a0|>=1.10.4,<2.0a0|>=1.9.3,<2.0a0|>=1.14.0,<2.0a0|>=1.13.*|>=1.14.*|1.9.*|>=1.18.5,<2.0a0|>=1.18.1,<2.0a0|>=1.15.1,<2.0a0']
ccdproc=1.3.0 -> numpy
astropy=2.0.3 -> numpy[version='>=1.9.3,<2.0a0']
scipy=1.0.0 -> numpy[version='>=1.9|>=1.9.3,<2.0a0']
numpy=1.13.3

Package scipy conflicts for:
ccdproc=1.3.0 -> reproject -> scipy[version='>=0.17|>=0.19|>=0.9|>=1.1']
scipy=1.0.0
ccdproc=1.3.0 -> scipy

Package llvm-openmp conflicts for:
ccdproc=1.3.0 -> scikit-image -> llvm-openmp[version='>=10.0.0|>=4.0.1']
numpy=1.13.3 -> mkl[version='>=2019.4,<2020.0a0'] -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=9.0.1|>=9.0.0']

Package astropy conflicts for:
ccdproc=1.3.0 -> astropy[version='>=1.0']
ccdproc=1.3.0 -> astroscrappy -> astropy[version='>=1|>=2.0|>=3.2']
astropy=2.0.3

Package python conflicts for:
pyqt=5.6.0 -> sip=4.18 -> python=3.4
ccdproc=1.3.0 -> astropy[version='>=1.0'] -> python[version='3.4.*|>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|<3.6*']
python=3.6.3
ccdproc=1.3.0 -> python[version='2.7.*|3.5.*|3.6.*|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
astropy=2.0.3 -> numpy -> python[version='3.4.*|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
scipy=1.0.0 -> python[version='2.7.*|3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0']
ipython=6.2.1 -> appnope -> python[version='2.7.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|3.4.*|>=3|>=3.5|>=3.7']
astropy=2.0.3 -> python[version='2.7.*|3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0']
numpy=1.13.3 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
pyqt=5.6.0 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
ipython=6.2.1 -> python[version='3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
scipy=1.0.0 -> numpy[version='>=1.9'] -> python[version='3.4.*|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
numpy=1.13.3 -> mkl-service[version='>=2,<3.0a0'] -> python[version='>=3.7,<3.8.0a0|>=3.9,<3.10.0a0']

Package ca-certificates conflicts for:
ccdproc=1.3.0 -> python -> ca-certificates
astropy=2.0.3 -> python=2.7 -> ca-certificates
pyqt=5.6.0 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
scipy=1.0.0 -> python=2.7 -> ca-certificates
numpy=1.13.3 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
python=3.6.3 -> openssl=1.0 -> ca-certificates

Package libcxxabi conflicts for:
scipy=1.0.0 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|0|4|3|2|hcfea43d_1']
python=3.6.3 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|0|4|3|2|hcfea43d_1']
numpy=1.13.3 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|0|4|3|2|hcfea43d_1']
pyqt=5.6.0 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|0|4|3|2|hcfea43d_1']

Package libgfortran-ng conflicts for:
astropy=2.0.3 -> numpy -> libgfortran-ng[version='>=3.0']
scipy=1.0.0 -> numpy[version='>=1.9'] -> libgfortran-ng[version='>=3.0']
ccdproc=1.3.0 -> numpy -> libgfortran-ng[version='>=3.0']

Package python_abi conflicts for:
astropy=2.0.3 -> numpy -> python_abi[version='3.6.*|3.6|3.8.*|3.7.*|3.9.*',build='*_cp39|*_cp36m|*_cp37m|*_pypy36_pp73|*_cp38']
numpy=1.13.3 -> python[version='>=3.6,<3.7.0a0'] -> python_abi[version='3.6.*|3.6|3.7.*|3.9.*|3.8.*',build='*_cp39|*_cp36m|*_cp37m|*_pypy36_pp73|*_cp38']
ccdproc=1.3.0 -> astropy[version='>=1.0'] -> python_abi[version='3.6|3.6.*|3.7.*|3.8.*|3.9.*',build='*_pypy36_pp73|*_cp36m|*_cp37m|*_cp39|*_cp38']
scipy=1.0.0 -> numpy[version='>=1.9'] -> python_abi[version='3.6.*|3.6|3.8.*|3.7.*|3.9.*',build='*_cp39|*_cp36m|*_cp37m|*_pypy36_pp73|*_cp38']
pyqt=5.6.0 -> python[version='>=3.6,<3.7.0a0'] -> python_abi==3.6[build=*_pypy36_pp73]
ipython=6.2.1 -> appnope -> python_abi[version='2.7.*|3.6|3.6.*|3.7.*|3.9.*|3.8.*',build='*_pypy36_pp73|*_cp36m|*_cp37m|*_cp39|*_cp38|*_cp27m']

Package setuptools conflicts for:
ccdproc=1.3.0 -> astropy[version='>=1.0'] -> setuptools
ipython=6.2.1 -> pygments -> setuptools
python=3.6.3 -> pip -> setuptools
astropy=2.0.3 -> pytest -> setuptools[version='>=40.0']

Package liblapacke conflicts for:
scipy=1.0.0 -> blas=[build=mkl] -> liblapacke[version='3.8.0|3.9.0|3.9.0',build='3_openblas|7_openblas|8_openblas|11_openblas|13_openblas|15_openblas|17_openblas|4_mkl|6_mkl|7_mkl|8_mkl|19_mkl|20_mkl|21_mkl|18_mkl|16_mkl|15_mkl|14_mkl|13_mkl|12_mkl|11_mkl|10_mkl|9_mkl|5_mkl|16_openblas|14_openblas|12_openblas|10_openblas|9_openblas|6_openblas|5_openblas|4_openblas|2_openblas']
numpy=1.13.3 -> blas=[build=openblas] -> liblapacke[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0',build='6_mkl|7_mkl|8_mkl|12_mkl|13_mkl|15_mkl|19_mkl|3_openblas|10_openblas|11_openblas|12_openblas|13_openblas|17_openblas|16_openblas|15_openblas|14_openblas|9_openblas|8_openblas|7_openblas|6_openblas|5_openblas|4_openblas|2_openblas|21_mkl|20_mkl|18_mkl|16_mkl|14_mkl|11_mkl|10_mkl|9_mkl|5_mkl|4_mkl']

Package six conflicts for:
ccdproc=1.3.0 -> reproject -> six[version='>=1.4|>=1.7.3']
astropy=2.0.3 -> pytest -> six[version='>=1.10.0']
numpy=1.13.3 -> mkl-service[version='>=2,<3.0a0'] -> six
ipython=6.2.1 -> prompt_toolkit[version='>=1.0.4,<2.0.0'] -> six[version='>=1.9.0']

Package pathlib2 conflicts for:
ipython=6.2.1 -> pickleshare -> pathlib2
astropy=2.0.3 -> pytest -> pathlib2[version='>=2.2.0']

Package decorator conflicts for:
ccdproc=1.3.0 -> decorator
ipython=6.2.1 -> decorator

Package libgfortran5 conflicts for:
numpy=1.13.3 -> blas=[build=openblas] -> libgfortran5[version='>=9.3.0']
ccdproc=1.3.0 -> scipy -> libgfortran5[version='>=9.3.0']
scipy=1.0.0 -> blas=[build=mkl] -> libgfortran5[version='>=9.3.0']
Note that strict channel priority may have removed packages required for satisfiability.
```

Do you have any suggestions?

**Comment by monodera** [comment]
Apparently, this was caused by 
```channel_priority: strict
```
in my `~/.condarc`.  When I commented out this line, I was able to

**Comment by mheida** [comment]
@joshwalawender I'm getting the same issue when installing through Anaconda with 
conda env create KeckObservatory/mospy_2018_macos:

Solving environment: failed

ResolvePackageNotFound: 
  - zope==1.0=py36_0

The mospy.yaml file you posted above is gone, could you post that again?
Thanks!

**Comment by joshwalawender** [comment]
@mheida I've updated the environment spec on the anaconda cloud.  Try running:

`conda env create KeckObservatory/mospy`

Note that I've removed the need to specify macOS or linux in the name.  If that works, I'll update the installation instructions and add the environment file to the repository.

**Comment by mheida** [comment]
Thanks @joshwalawender! The installation seems to have worked, but I'm now getting a 'mospy: command not found' error when I try to run things and indeed there is no mospy executable in envs/mospy/bin (or anywhere else in envs/mospy as far as I can tell).

**Comment by monodera** [comment]
Recently, I found that the default setuptools installed along the mospy.yaml is >=58 (maybe with the latest conda-forge dependency), but it need to be earlier than that to install the MOSFIRE DRP. 

https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2

Also, astropy-helpers should be explicitly installed with a specific version around 3.2.

Eventually, I used the following yaml file so that no additional package is required at the stage of the DRP installation.

```yaml
name: mospy
channels:
  - conda-forge
  - defaults
dependencies:
  - ccdproc=1.3.0
  - numpy=1.13.3
  - scipy=1.0.0
  - python=3.6.3
  - astropy=2.0.3
  - pyqt=5.6.0
  - ipython=6.2.1
  - setuptools=57
  - pip
  - pip:
    - astropy-helpers==3.2.2
```

**Comment by analuisagm** [comment]
I share my experience.

conda env create KeckObservatory/mospy seems to work but then with 
python setup.py install
I got an error
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.  Attempting download instead.
Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    from astropy_helpers.setup_helpers import (
ModuleNotFoundError: No module named 'astropy_helpers.setup_helpers'

I fix it using:

pip install setuptools==57
pip install astropy-helpers==3.2.2

and running again:
python setup.py install 
which now finished the process successfully.

Thank you to all for share the information.
