### ISSUE TITLE
AutoDriver fails if handle was run with relative path

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/MosfireDRP#65]
A call to `fname_to_path` is missing the options input the handling the case of a non-absolute path.

```
> mospy AutoDriver
slitmask mode
Generating automatic driver file Driver.py
Traceback (most recent call last):
  File "/sdr1data/mosfiredata/anaconda2/bin/AutoDriver.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jwalawender/git/MosfireDRP/scripts/AutoDriver.py", line 422, in <module>
    mydriver.printMaskAndBand()
  File "/home/jwalawender/git/MosfireDRP/scripts/AutoDriver.py", line 71, in printMaskAndBand
    else: path = os.path.join(fname_to_path(fname[0]), fname[0])
TypeError: fname_to_path() takes exactly 2 arguments (1 given)
```

**Comment by joshwalawender** [comment]
Fixed by #97
